### ISSUE TITLE
Poor description

### ISSUE THREAD

**Issue by nise** [devopsfaith/krakend-examples#3]
Why shall I test this krakenD example? There is no description, no motivation, and no sense at all visible.

**Comment by kpacha** [comment]
you're right. the project is just a bunch of demonstrations of simple integrations with other components of the KrakenD ecosystem we pushed in order to help users build their own more complex solutions when the [CE](https://github.com/openrm/krakend-ce) does not suit their requirements. 

we can not give it the love it deserves and are open to every type of contributions .
